### ISSUE TITLE
where save SONY_ADCP.py file?

### ISSUE THREAD

**Issue by henriquejourdan** [tokyotexture/homeassistant-custom-components#1]
Hi
Im trying to make this work but where should I save SONY_ADCP.py?
Tried 
config/custom_components/
config/custom_components/sony_adcp
config/custom_components/sony_adcp/switch
Greetings
LP

**Comment by tokyotexture** [comment]
I migrated off of Home Assistant a while back, so I can't test it for you, but I think it should be config/custom_components/switch/   . There was a change in folder structure from HA's perspective a while back, so I'm not 100% sure, but I think that's the right one now.
If you can try it, and if it works, I'll update the documentation to make it more clear.

**Comment by GizmoGoody** [comment]
@henriquejourdan Did you figure out the right place to place this?
